version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE: mongodb://mongo:27017/CSFDB
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: